### ISSUE TITLE
Tour: button for tickets within tour date card

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#10]
## USER STORY
As a user, I want to see a button next to the tour dates that allows me to buy tickets

## AC
WHEN I view the tour schedule
THEN there should be a bootstrap button at the right end of the cards
AND when the user clicks the button, an alert window opens that says "SOLD OUT!"

## DEV NOTES
![Screen Shot 2020-02-10 at 6 28 44 PM](https://user-images.githubusercontent.com/52139891/74202822-2cfc5980-4c33-11ea-8ddc-c4c020db783a.png)

* use this code for the button:
```html
<button type="button" class="btn btn-lg btn-light" data-toggle="popover" title="SOLD OUT" data-content="Please select another event.">Buy Tickets</button>
```
* optional: Style the button to fit the theme of the site (color, etc)
* edit the `makeTourCards` function so that the button is part of the printToDom when the card is created.
* this button has bootstrap that will do its own Popover when clicked, to indicate SOLD OUT

**Comment by joeypetrone** [comment]
![image](https://user-images.githubusercontent.com/59629666/74079650-13bf9700-4a00-11ea-88ff-4035fde31bed.png)

**Comment by joeypetrone** [comment]
I suggest using a bootstrap popover for this:

https://getbootstrap.com/docs/4.0/components/popovers/

**Comment by zoeames** [comment]
tell me more about what happens when the button is clicked.  an event listener?  that calls some kind of function?

**Comment by olamide87** [comment]
We discussed as a group and decided that the pop over was inappropriate so we decided to uses an alert instead.
