### ISSUE TITLE
Members: members bio cards

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#12]
## USER STORY
As a user, I want to see information about the band as a group, as well as the individual members.

## AC
WHEN the page loads, there should be large, horizontal bootstrap cards for 1. the band, and 2. each of the members
THEN each card should have a square image that takes up the left end of the card
AND there should be a title for each card (member name)
AND there should be a description under each title (member's band role)
AND there should be some lorem ipsum (metal ipsum) text to represent a bio/description of each 
AND the background of the cards should be WHITE
AND name/title should be DARK GRAY

## DEV NOTES
![Screen Shot 2020-02-10 at 6 23 23 PM](https://user-images.githubusercontent.com/52139891/74202567-6d0f0c80-4c32-11ea-9eed-df91230990fb.png)

* use this code for the cards:
``` html
<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
  </div>
</div>
```
* create an array called `bios` with Objects for the cards, like:
```
{
imageUrl: "image.jpg",
name: "Steve",
role: "lead singer",
bio: "lorem ipsum"
}
```
* create a container div for this in members.html, called `bio-container`
* create a function called `makeBioCards` that loops through the `bios` array and uses printToDom to create the cards

**Comment by zoeames** [comment]
what kind of function?  do you need any divs in the html?

**Comment by spookycutie08** [comment]
updated comments for specificity of container and function name
