### ISSUE TITLE
Merch: cart div

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#14]
## USER STORY
As a user, I want to be able to add items to a virtual shopping cart that I want to purchase

## AC
WHEN the user clicks the "BUY" button on an item
THEN it moves a COPY of the card into a ```<div>``` at the bottom of the page
AND continues to add items when more are clicked
AND the background color should be green: 8FDC97

## DEV NOTES
* Shopping cart div should be sorta like this:
![Screen Shot 2020-02-06 at 7 44 13 PM](https://user-images.githubusercontent.com/52139891/73993850-16938c80-4919-11ea-8c02-f84b5460958f.png)
* create a separate div under the ```store-container```, called ```cart-container```
* when the "BUY" button is clicked in an item, an eventListener (that was already created in the merch item cards ticket #13 ) should call a function ```buyItem``` that adds that item card to a separate array called ```cart``` (next two steps)
* ```buyItem``` should also call the function ```makeMerchCards``` to re-print the merch in ```store-container```
* ```buyItem``` should also call another function called ```printCart``` that uses printToDom to create new cards in ```cart-container```

## Whoever does this ticket: the cutoff is this:
- it needs to make a copy of the merch item inside the cart, nothing more.
- the other ticket for Remove #20 will address the button change and removing items

**Comment by zoeames** [comment]
how do you know what item has been clicked on?  

* also make the remove functionality a separate ticket

**Comment by spookycutie08** [comment]
* ticket #13 addresses the button click by assigning the event listener when the item prints to DOM.
* separate ticket created for remove button (#20 )
