### ISSUE TITLE
style cleanup ticket

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#17]
## General Style Cleanup
Review final product and make sure:
* All pages have the same style "feel" - black, green, gray, blue - font default bootstrap
* Edit colors, sizes of text and/or cards, etc. as needed
* All horizontal cards should take up width of the page, minus a margin of 30px
* H1 for section title
* H2 for card titles
* `<p>` for details inside
* All pages are double-checked for typos

**Comment by zoeames** [comment]
have you all agreed on what your colors, fonts, text sizes are going to be yet?

**Comment by spookycutie08** [comment]
### Things that might need a look:
* NavBar: discussed possibly updating logo placement, and I think we can probably remove the H1 tags for each page title (somewhat redundant, since the navbar has an Active attribute for each page)
* NavBar Logo: Alternatively, can consider using the white logo that I used as album art (if that fits better into the aesthetic of the navbar area)
`https://i1.sndcdn.com/artworks-000053909121-6qx5rc-t500x500.jpg`
* Tour Page: the light gray div for date has slight size difference on the San Francisco card #DONE /BW
* Music Page: images are responsive, but certain device sizes (about 768 - 1000 px width) leave a gap beneath the images
* Main.js : I think `const events` is moot now, since this is declared in the switch statement, and we're not calling `events` anywhere... right?

**Comment by bwhitworth** [comment]
## Updated the tour page issue (change the date so it doesn't resize weirdly)

**Comment by spookycutie08** [comment]
I'm going to call this complete, since Joey and Beth looked over this pretty thoroughly today. Great job guys! 👍

**Comment by joeypetrone** [comment]
Hey! I didn't approve this! 👎
