### ISSUE TITLE
navbar/setup

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#3]
## USER STORY
As a user, at the top of every page, there should be a navbar that lets me navigate to other pages

## AC
WHEN the page loads
THEN I should see a bootstrap navbar at the top
AND it should have the winterlizard logo to the left (can be separate from navbar)
AND it should have links for Music, Tour, Members and Merch on the right
AND when I click any of those links I should see an h1 tag that says the page name.

## DEV NOTES
* Create main.css and set background color to black
* Create index.html, music.html, tour.html, members.html, merch.html - boilerplate HTML and h1 tag with page name on each one
* Add the correct bootstrap link tag to main.css in each html file:
```
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
```
* Add link to `main.css` underneath the bootstrap link in each html file
* Use this bootstrap navbar (hard code to each html file):
```
<nav class="navbar navbar-dark bg-dark">
  <!-- Navbar content -->
</nav>
```
* inside the navbar, where it says <---navbar content --->, add an unordered list of a ref links to each of the pages - Home, Music, Tour, Members, and Merch 
* link the nav-links to the correct html files
* make sure there is no search bar in the navbar
* logo link: https://www.metal-archives.com/images/3/5/4/0/3540369098_logo.jpg?1946

**Comment by olamide87** [comment]
//Navbar

<nav class="navbar navbar-dark bg-dark">
  
</nav>

**Comment by olamide87** [comment]
Ready for pull request
