### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#4]
## USER STORY
As a user, at the bottom of every page, I want to see a footer with copyright © 2020 band name 

## AC
WHEN the page loads
THEN I should see a footer
AND it should have the band name
AND it should have a copyright symbol `©`
AND it should have the year 2020
AND it should have a top border that is dark gray
AND all of the text should be white

## DEV NOTES
* on each html file, hard-code the footer into the bottom of the `<body>` div
* use this bootstrap footer: 
``` html
<footer class="page-footer font-small special-color-dark pt-4">
  <div class="footer-copyright text-center py-3">© 2020 Copyright: WinterLizard
    <a href="https://mdbootstrap.com/education/bootstrap/"> MDBootstrap.com</a>
  </div>
</footer>
```

**Comment by joeypetrone** [comment]
https://mdbootstrap.com/docs/jquery/navigation/footer/
