### ISSUE TITLE
Home: news cards

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#6]
## USER STORY
As a user, I want to see cards with current news about the band display beneath the photo carousel

## AC
WHEN the page loads
THEN I should see a set of bootstrap cards (horizontal cards)
AND they should display one per row
AND each card should have a photo on the left end of card
AND each card should have some information about a news item, such as album release, what the band has been up to, announcements, pet lizards, etc.
AND the section should have a title of "NEWS"

## DEV NOTES
<img width="482" alt="Screen Shot 2020-02-10 at 6 03 52 PM" src="https://user-images.githubusercontent.com/52139891/74201538-b3af3780-4c2f-11ea-93fb-3be87589df63.png">

* use bootstrap cards:
```html
<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
  </div>
</div>
```
* create an array with 4 Objects, like:
```
{
date: '01/01/2020',
imageUrl: "something.jpg",
desc: "lorem ipsum"
}
```
* create a function called `makeNewsCards` that loops through the array with printToDom function to create a card for each News Object
* images need to fill the card vertically and be square
* background of cards should be this shade of green: 8FDC97
* there should be a title for date of the news
* text color should be black

**Comment by olamide87** [comment]
// horizontal cards//
<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

**Comment by olamide87** [comment]
```html
#3 8FDC97
```

**Comment by joeypetrone** [comment]
May need a title for each news story

**Comment by zoeames** [comment]
are you doing the looping in the printToDom function?  or do you need to make another function?
