### ISSUE TITLE
Home: subscribe form

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#7]
## USER STORY
As a user, I should be able to subscribe to the email list for band news

## AC
WHEN the home page loads
THEN an input form will be at the bottom of the page (below NEWS section)
AND it should have a title of SUBCRIBE
AND it should have an input for email address with a label or placeholder that says "Email Address"
AND it should have a Submit button next to the input field
AND the colors should fit the black/white/green theme of the site (maybe swithc btn-rpimary for btn-dark)
AND an error message should appear if the user tries to submit a blank input

## DEV NOTES
* use this code:
```html
<form class="form-inline">
<div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
 <button type="submit" class="btn btn-secondary">Submit</button>
</form>
```

**Comment by joeypetrone** [comment]
We might want to have an error message when the field is empty or not a correct email. I think I saw on bootstrap that this is fairly easy to do.  Also, we should notify the user that their email has been subscribed when they press the button.

**Comment by zoeames** [comment]
more details needed here - how are you doing the input field validation?  do you need to write any functions in your JS?

**Comment by spookycutie08** [comment]
updated code for form validation

**Comment by joeypetrone** [comment]
I used this for validation instead of bootstrap.

https://www.w3resource.com/javascript/form/email-validation.php
