### ISSUE TITLE
Music: album cards

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#8]
## USER STORY
As a user, when the Music page loads, I want to see the discography of the band, with the tracks listed

## AC
WHEN the Music page loads
THEN a large, horizontal (bootstrap) card should appear for each album
AND each card should have album art at the left end
AND album art should be square
AND the album title, release date, and numbered list of tracks should display on the right
AND the Album Title should be a link to the Soundcloud page for that album

## DEV NOTES
![Screen Shot 2020-02-10 at 6 26 25 PM](https://user-images.githubusercontent.com/52139891/74202693-d98a0b80-4c32-11ea-86b3-cac0c02c19f9.png)

* Use this code for cards (can modify as needed):
``` html
<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
  </div>
</div>
```
* create an array of Objects(albums) called ```albums``` like:
```
{
title: "Something Morbid",
albumArt: "something.jpg",
soundLink: "soundcloud.com/thisthing",
releaseDate: "01/01/2020",
tracks: [Track1, Track2, Track3]
}
```
* creata a container div in music.html called `album-container` for the cards to live in
* create a function called `makeAlbumCards` that loops through the array with printToDom function and prints the cards into the `album-container` div
* card background should be this shade of blue: #0052cc
* text color should be WHITE
* Make sure the link text is WHITE ("transform?")

**Comment by joeypetrone** [comment]
For styling links:
https://www.w3schools.com/css/css_link.asp

**Comment by zoeames** [comment]
this ticket needs A LOT more dev notes?  How are you building up the domString for the array within the object?

**Comment by spookycutie08** [comment]
* changed color theme to match the rest of site (background gray instead of blue)
* changed links to listen to albums to a separate text (not the title, to be more obvious)
