### ISSUE TITLE
Tour: cards for tour dates

### ISSUE THREAD

**Issue by spookycutie08** [nss-evening-cohort-11/bands-winter-lizard#9]
## USER STORY
As a user, I want to see a list of upcoming tour dates and details

## AC
WHEN the page loads, there should be a section with a title of "TOUR SCHEDULE"
THEN there should be bootstrap cards of the upcoming tour dates and details about the venue
AND the background of the card should be dark gray
AND the text should be WHITE
AND the DATE section should span the card, vertically (try to be square), on the left end
AND the DATE section should be a lighter shade of gray

## DEV NOTES
![Screen Shot 2020-02-10 at 6 29 41 PM](https://user-images.githubusercontent.com/52139891/74202861-50bf9f80-4c33-11ea-81d5-04f6c1203092.png)

* use this bootstrap code for the card: 
```html
<div class="card">
  <h5 class="card-header">Featured</h5>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
  </div>
</div>
```
* create an array of Objects called ```tourDates``` like:
```
{
date: "01/01/2020",
city: "Sacramento",
state: "CA",
venue: "The Dungeon",
}
```
* create a container div called `tour-container` for the cards to live in
* create a function called `makeTourCards` that loops through the array `tourDates` and uses printToDom to create the cards inside the container div

**Comment by joeypetrone** [comment]
Similar to this minus the ticket button:
![image](https://user-images.githubusercontent.com/59629666/74079611-972cb880-49ff-11ea-970d-63e1477f137c.png)

**Comment by zoeames** [comment]
what kind of function?

**Comment by spookycutie08** [comment]
updated specifics of function names, etc.
